config/routes.rb
Reddit::Application.routes.draw do
  resources :users

  match 'users/new' => 'users#new', :via => :post
  match 'users/show' => 'users#show', :via => :post

  match 'queries' => 'users#show', :via => :get
  match 'search' => 'users#new', :via => :get

  root :to => "users#index"

end

app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessible :query, :user_id
  belongs_to :user
  has_many :search_results
end

app/models/search_result.rb
class SearchResult < ActiveRecord::Base
  attr_accessible :data
  belongs_to :search
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
  has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require "net/http"
  require "uri"
  require 'reddit_search_service'

  def new
    @query = params[:query]
    @user = params[:username] ? User.find_or_create_by_username(params[:username]) : User.new
    if @query
      search = @user.searches.create!(:query => @query)
      data = RedditSearchService.search( @query )
      @links = []
      data["data"]["children"].each do |article|
        @links << { :title => article["data"]["title"], :url => article["data"]["url"] }
        search.search_results.create! :data => article["data"]["title"]
      end
    end
  end

  def show
    @user = User.find_by_username(params[:username])
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<%= link_to "Search via Reddit", search_path %>
<%= link_to "Get searches per user", queries_path %>

app/views/users/new.html.erb
<%= form_tag do %>
    <div class="field">
      <label>Username</label><br />
      <%= text_field_tag :username, @user.username %>
    </div>

    <div class="field">
      <label>Query</label><br />
      <%= text_field_tag :query, @query %>
    </div>

    <div class="actions">
      <%= submit_tag value = 'Search reddit' %>
    </div>
<% end %>

<% if @links %>
<% @links.each do |link| %>
    <%= link_to link[:title], link[:url] %></br>
<% end %>
<% end %>

app/views/users/show.html.erb
<%= 'User ' + params[:username] + ' not found' if !@user and request.method.eql?("POST")%>

<% if @user %>
    <H1> User <%= @user.username %> </H1>
    <% @user.searches.each do |search| %>
        <h2><span onclick="$('#res_<%=search.id%>').toggle();" style="cursor:pointer">+</span><%= search.query + " " + search.search_results.count.to_s + " results"%></h2>
        <div id="res_<%=search.id%>" style="display:none">
          <% search.search_results.each do |res| %>
              <%= res.data %></br>
          <% end %>
        </div>
    <% end %>
<% else %>
    <%= form_tag do %>
        <div class="field">
          <label>Username</label><br />
          <%= text_field_tag :username %>
        </div>

        <div class="actions">
          <%= submit_tag value = 'Show queries' %>
        </div>
    <% end %>
<% end %>